# Generated by Django 5.2.9 on 2026-07-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('visit_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Emergency', 'Emergency'), ('Follow-up', 'Follow-up'), ('Screening', 'Screening'), ('Other', 'Other')], max_length=50)),
                ('reason', models.TextField()),
                ('healthcare_provider', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
    ]
