# Generated by Django 6.0.7 on 2026-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=50, unique=True)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('Health Centre', 'Health Centre'), ('Other', 'Other')], max_length=50)),
                ('country_code', models.CharField(default='ZW', max_length=2)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('physical_address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fhir_organization_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
