# Generated by Django 6.0.7 on 2026-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Laboratory', 'Laboratory'), ('Shared Health Record', 'Shared Health Record'), ('Client Registry', 'Client Registry'), ('DHIS2', 'DHIS2'), ('Pharmacy', 'Pharmacy'), ('Other', 'Other')], max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('fhir_version', models.CharField(default='R4', max_length=20)),
                ('base_url', models.URLField()),
                ('authentication', models.CharField(choices=[('Bearer Token', 'Bearer Token'), ('API Key', 'API Key'), ('OAuth2', 'OAuth2'), ('Basic Auth', 'Basic Auth')], default='Bearer Token', max_length=50)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Maintenance', 'Maintenance')], default='Connected', max_length=30)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_name'],
            },
        ),
    ]
