# Generated by Django 6.0.7 on 2026-07-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Harare EHR Production Key')", max_length=150)),
                ('key_hash', models.CharField(help_text='Secure hash of the token', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='First few characters for identification', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.connectedsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
