# Generated by Django 6.0.7 on 2026-07-30 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='FhirTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Inbound', 'Inbound (Received from external system)'), ('Outbound', 'Outbound (Sent to external system)')], default='Inbound', max_length=20)),
                ('resource_type', models.CharField(help_text='e.g., Patient, Organization, Bundle', max_length=50)),
                ('method', models.CharField(help_text='GET, POST, PUT, etc.', max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(help_text='HTTP status code returned')),
                ('payload', models.TextField(help_text='Raw JSON payload sent or received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.connectedsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
