# Generated by Django 5.2.9 on 2026-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('work_email', models.EmailField(help_text='Institutional work email required.', max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('requested_role', models.CharField(choices=[('nurse', 'Nurse'), ('administrator', 'Administrator')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
