# Generated by Django 5.2.9 on 2026-07-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='work_email',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='email',
            field=models.EmailField(default='temp@example.com', help_text='Personal or institutional email.', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='staff_id',
            field=models.CharField(default='00000', help_text='MOHCC or Facility Employee ID', max_length=50),
            preserve_default=False,
        ),
    ]
