# Generated by Django 5.2.9 on 2026-07-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIVTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_facility', models.CharField(max_length=200)),
                ('test_type', models.CharField(default='HIV Test', max_length=100)),
                ('sample_collection_date', models.DateField()),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Indeterminate', 'Indeterminate')], default='Pending', max_length=20)),
                ('result_submitted_date', models.DateField(blank=True, null=True)),
                ('result_submitter', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Sample Collected', 'Sample Collected'), ('Result Submitted', 'Result Submitted')], default='Requested', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiv_tests', to='patients.patient')),
            ],
        ),
    ]
