# Generated by Django 5.2.9 on 2026-07-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiv_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivtest',
            name='test_type',
            field=models.CharField(choices=[('HIV', 'HIV'), ('Malaria', 'Malaria'), ('Tuberculosis', 'Tuberculosis'), ('Maternal Care', 'Maternal Care')], default='HIV', max_length=100),
        ),
    ]
