# Generated by Django 6.1 on 2026-08-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('VIEW', 'View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('OTHER', 'Other'), ('EMERGENCY_OVERRIDE', 'Emergency Override')], max_length=20),
        ),
    ]
