# Generated by Django 6.0.7 on 2026-07-28 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_remove_externalpatientidentifier_facility_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('GENERAL', 'General Care'), ('REFERRAL', 'Referral Sharing'), ('LABORATORY', 'Laboratory Sharing'), ('RESEARCH', 'Research')], max_length=30)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired')], default='GRANTED', max_length=20)),
                ('granted_by', models.CharField(max_length=200)),
                ('granted_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('emergency_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'consent_type'), name='unique_patient_consent')],
            },
        ),
    ]
