# Generated by Django 6.0.7 on 2026-07-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPatientIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=200)),
                ('identifier_type', models.CharField(default='Facility Patient ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='patients.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system_name', 'identifier'), name='unique_external_patient_identifier')],
            },
        ),
    ]
