# Generated by Django 6.0.7 on 2026-07-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0002_externalpatientidentifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalpatientidentifier',
            name='facility_name',
        ),
        migrations.AddField(
            model_name='externalpatientidentifier',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_identifiers', to='facilities.facility'),
        ),
    ]
