from rest_framework import serializers
from patients.models import Patient, ExternalPatientIdentifier
from facilities.models import Facility

class FHIRPatientSerializer(serializers.ModelSerializer):
    class Meta:
        model = Patient
        fields = [
            'oph_id', 'national_id', 'first_name', 'last_name', 
            'date_of_birth', 'gender', 'phone_number', 'address', 
            'external_identifiers'
        ]
        # Tells DRF to ignore these fields during raw direct model validation
        read_only_fields = ['oph_id', 'external_identifiers']

    def to_internal_value(self, data):
        """
        Translates incoming FHIR JSON -> Flat Django Model data
        Enforces OPH-ID generation and National ID uniqueness.
        """
        if data.get('resourceType') != 'Patient':
            raise serializers.ValidationError({"resourceType": "Invalid resourceType. Expected 'Patient'."})

        # -------------------------------------------------------------
        # 1. Enforce No Client-Supplied OPH-ID on POST (Creation)
        # -------------------------------------------------------------
        is_create = self.instance is None  

        if is_create:
            if data.get('id'):
                raise serializers.ValidationError({
                    "id": "OPH-IDs are generated by OnePatient Hub. Do not include an 'id' field on POST requests."
                })

            has_oph_id = any(
                i.get('system') == 'http://onepatienthub.zw/identifier/oph-id' 
                for i in data.get('identifier', [])
            )
            if has_oph_id:
                raise serializers.ValidationError({
                    "identifier": "OPH-IDs are assigned centrally by OnePatient Hub. Remove the OPH-ID identifier from your POST request."
                })

        # -------------------------------------------------------------
        # 2. Extract Data
        # -------------------------------------------------------------
        names = data.get('name', [{}])[0]
        last_name = names.get('family', 'Unknown')
        given_names = names.get('given', ['Unknown'])
        first_name = given_names[0] if given_names else 'Unknown'

        fhir_gender = data.get('gender', 'unknown')
        django_gender = {'male': 'Male', 'female': 'Female'}.get(fhir_gender, 'Male')

        phone_number = next(
            (t.get('value', '') for t in data.get('telecom', []) if t.get('system') == 'phone'), 
            ''
        )
        addresses = data.get('address', [{}])
        address = addresses[0].get('text', '') if addresses else ''

        national_id = next(
            (i.get('value', '') for i in data.get('identifier', []) if i.get('system') == 'http://onepatienthub.zw/identifier/national-id'), 
            ''
        )

        if not national_id:
            raise serializers.ValidationError({"identifier": "A National ID identifier is required."})

        # -------------------------------------------------------------
        # 3. Check for Duplicate National ID
        # -------------------------------------------------------------
        if is_create and Patient.objects.filter(national_id=national_id).exists():
            existing_patient = Patient.objects.get(national_id=national_id)
            raise serializers.ValidationError({
                "national_id": f"A patient with National ID '{national_id}' already exists in OnePatient Hub (OPH-ID: {existing_patient.oph_id}). Use PUT /api/fhir/Patient/{existing_patient.oph_id} to update their record."
            })

        # Store raw incoming identifiers array so create/update can process them horizontally
        self.raw_identifiers = data.get('identifier', [])

        # Map to internal Django model fields
        internal_data = {
            'first_name': first_name,
            'last_name': last_name,
            'gender': django_gender,
            'date_of_birth': data.get('birthDate'),
            'phone_number': phone_number,
            'address': address,
            'national_id': national_id
        }

        return super().to_internal_value(internal_data)

    def create(self, validated_data):
        """
        Creates the patient and links any incoming facility external identifiers horizontally.
        """
        patient = Patient.objects.create(**validated_data)
        self._sync_external_identifiers(patient, getattr(self, 'raw_identifiers', []))
        return patient

    def update(self, instance, validated_data):
        """
        Updates the patient core info and synchronizes external identifiers.
        """
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        instance.save()

        if hasattr(self, 'raw_identifiers'):
            self._sync_external_identifiers(instance, self.raw_identifiers)

        return instance

    def _sync_external_identifiers(self, patient, identifiers_list):
        """
        Helper method to parse FHIR identifiers and map secondary facility IDs horizontally.
        """
        for ident in identifiers_list:
            system = ident.get('system', '')
            value = ident.get('value', '')

            # Skip system IDs like national-id or oph-id
            if 'national-id' in system or 'oph-id' in system:
                continue

            if system and value:
                # Try to map facility if system URL references a facility namespace or check assigner text
                assigner = ident.get('assigner', {})
                facility_name = assigner.get('display')
                
                facility = None
                if facility_name:
                    facility = Facility.objects.filter(facility_name__icontains=facility_name).first()

                # Update or create the horizontal tracker record
                ExternalPatientIdentifier.objects.update_or_create(
                    system_name=system,
                    identifier=value,
                    defaults={
                        'patient': patient,
                        'facility': facility,
                        'identifier_type': ident.get('type', {}).get('text', 'Facility Patient ID')
                    }
                )

    def to_representation(self, instance):
        """
        Converts the Django Patient model into a standard FHIR Patient resource.
        """
        gender_mapping = {
            'Male': 'male',
            'Female': 'female',
        }
        fhir_gender = gender_mapping.get(instance.gender, 'unknown')

        identifiers = [
            {
                "use": "official",
                "type": {
                    "coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0203", "code": "MR", "display": "Medical record number"}]
                },
                "system": "http://onepatienthub.zw/identifier/oph-id",
                "value": str(instance.oph_id)
            },
            {
                "use": "usual",
                "type": {
                    "coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0203", "code": "NNZWE", "display": "National Person Identifier"}]
                },
                "system": "http://onepatienthub.zw/identifier/national-id",
                "value": str(instance.national_id)
            }
        ]

        for ext_id in instance.external_identifiers.all():
            facility_name = ext_id.facility.facility_name if ext_id.facility else "Unknown Facility"
            facility_system_name = ext_id.system_name.replace(' ', '-').lower() if ext_id.system_name else "unknown-system"
            
            identifiers.append({
                "use": "secondary",
                "type": {
                    "text": ext_id.identifier_type
                },
                "system": f"http://onepatienthub.zw/identifier/facility/{facility_system_name}",
                "value": str(ext_id.identifier),
                "assigner": {
                    "display": facility_name
                }
            })

        fhir_patient = {
            "resourceType": "Patient",
            "id": str(instance.oph_id),
            "identifier": identifiers,
            "active": True,
            "name": [
                {
                    "use": "official",
                    "family": instance.last_name,
                    "given": [instance.first_name]
                }
            ],
            "telecom": [
                {
                    "system": "phone",
                    "value": instance.phone_number,
                    "use": "mobile"
                }
            ],
            "gender": fhir_gender,
            "birthDate": str(instance.date_of_birth) if instance.date_of_birth else None,
            "address": [
                {
                    "use": "home",
                    "text": instance.address
                }
            ]
        }

        return fhir_patient


class FHIROrganizationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Facility
        fields = [
            'facility_id', 'facility_name', 'facility_type', 
            'country_code', 'province', 'district', 'physical_address', 
            'phone_number', 'email', 'fhir_organization_id', 'is_active'
        ]

    def to_representation(self, instance):
        """
        Converts the Django Facility model into a standard FHIR Organization resource.
        """
        fhir_organization = {
            "resourceType": "Organization",
            "id": str(instance.facility_id),
            "identifier": [
                {
                    "use": "official",
                    "system": "http://onepatienthub.zw/identifier/facility-id",
                    "value": str(instance.facility_id)
                }
            ],
            "active": instance.is_active,
            "type": [
                {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                            "code": "prov",
                            "display": "Healthcare Provider"
                        }
                    ],
                    "text": instance.facility_type
                }
            ],
            "name": instance.facility_name,
            "telecom": [],
            "address": [
                {
                    "use": "work",
                    "type": "physical",
                    "text": instance.physical_address,
                    "district": instance.district,
                    "state": instance.province,
                    "country": instance.country_code
                }
            ]
        }

        if instance.phone_number:
            fhir_organization["telecom"].append({
                "system": "phone",
                "value": instance.phone_number,
                "use": "work"
            })

        if instance.email:
            fhir_organization["telecom"].append({
                "system": "email",
                "value": instance.email,
                "use": "work"
            })

        if instance.fhir_organization_id:
            fhir_organization["identifier"].append({
                "use": "secondary",
                "system": "http://onepatienthub.zw/identifier/fhir-org-id",
                "value": str(instance.fhir_organization_id)
            })

        return fhir_organization